units: SraTableFiltered.txt        # Complete the tab sep value file with the path to the files and their conditions

### Definition of the path Snakemake has to create
working_dir: "temp/"
result_dir: "results/"
